name: "aider-chat-action"
description: "Easiest way to run Aider in your GitHub Actions workflow"
inputs:
  api_key_env_name:
    description: "The name of the environment variable. For example, OPENAI_API_KEY, ANTHROPIC_API_KEY, etc. See more info: https://aider.chat/docs/llms.html"
    # Will be required when the old way of passing API keys is removed.
    required: false
    default: ""
  api_key_env_value:
    description: "The API Key to use as the value of the 'api_key_env_name'"
    # Will be required when the old way of passing API keys is removed.
    required: false
    default: ""
  model:
    description: "Model to use for Aider"
    required: true
  branch:
    description: "Branch to run Aider on"
    default: "main"
    required: false
  aider_args:
    description: "Space-delimited args to pass to aider (e.g. --yes --message 'Make the dashboard sidebar purple')"
    required: true
  # Deprecated way of passing API keys. Will be removed in future versions.
  openai_api_key:
    description: "[Deprecated - use api_key_env_name and api_key_env_value instead] OpenAI API Key"
    default: ""
    required: false
  anthropic_api_key:
    description: "[Deprecated - use api_key_env_name and api_key_env_value instead] Anthropic API Key"
    default: ""
    required: false
  gemini_api_key:
    description: "[Deprecated - use api_key_env_name and api_key_env_value instead] Gemini API Key"
    default: ""
    required: false
  groq_api_key:
    description: "[Deprecated - use api_key_env_name and api_key_env_value instead] Groq API Key"
    default: ""
    required: false
  cohere_api_key:
    description: "[Deprecated - use api_key_env_name and api_key_env_value instead] Cohere API Key"
    default: ""
    required: false
  deepseek_api_key:
    description: "[Deprecated - use api_key_env_name and api_key_env_value instead] Deepseek API Key"
    default: ""
    required: false
  openrouter_api_key:
    description: "[Deprecated - use api_key_env_name and api_key_env_value instead] OpenRouter API Key"
    default: ""
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    API_KEY_ENV_NAME: ${{ inputs.api_key_env_name }}
    API_KEY_ENV_VALUE: ${{ inputs.api_key_env_value }}
    FEATURE_REF: ${{ inputs.branch }}
    MODEL: ${{ inputs.model }}
    AIDER_ARGS: ${{ inputs.aider_args }}
    # Deprecated way of passing API keys. Will be removed in future versions.
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
    GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
    GROQ_API_KEY: ${{ inputs.groq_api_key }}
    COHERE_API_KEY: ${{ inputs.cohere_api_key }}
    DEEPSEEK_API_KEY: ${{ inputs.deepseek_api_key }}
    OPENROUTER_API_KEY: ${{ inputs.openrouter_api_key }}

branding:
  icon: "cpu"
  color: "white"
